# Generated by Django 5.0.13 on 2026-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lancamento_omie', models.BigIntegerField(unique=True, verbose_name='Código do lançamento Omie')),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True, verbose_name='Código do cliente/fornecedor')),
                ('codigo_categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código da categoria')),
                ('codigo_tipo_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do tipo de documento')),
                ('chave_nfe', models.CharField(blank=True, max_length=60, null=True, verbose_name='Chave NFe')),
                ('numero_documento_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do documento fiscal')),
                ('numero_parcela', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número da parcela')),
                ('numero_pedido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do pedido')),
                ('id_conta_corrente', models.BigIntegerField(blank=True, null=True, verbose_name='ID da conta corrente')),
                ('id_origem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Origem')),
                ('operacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Operação')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Data de previsão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('status_titulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status do título')),
                ('valor_documento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do documento')),
                ('retem_cofins', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_csll', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_inss', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_ir', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_iss', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_pis', models.CharField(blank=True, max_length=1, null=True)),
                ('info_cimpapi', models.CharField(blank=True, max_length=1, null=True, verbose_name='Importado pela API')),
                ('info_d_inc', models.DateField(blank=True, null=True, verbose_name='Data de inclusão')),
                ('info_h_inc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de inclusão')),
                ('info_u_inc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuário de inclusão')),
                ('info_d_alt', models.DateField(blank=True, null=True, verbose_name='Data de alteração')),
                ('info_h_alt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de alteração')),
                ('info_u_alt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuário de alteração')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento', '-codigo_lancamento_omie'],
            },
        ),
    ]
