# Generated by Django 5.0.13 on 2026-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_superior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria superior')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('codigo_dre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código DRE')),
                ('conta_despesa', models.CharField(blank=True, max_length=1, null=True, verbose_name='Conta despesa')),
                ('conta_inativa', models.CharField(blank=True, max_length=1, null=True, verbose_name='Conta inativa')),
                ('conta_receita', models.CharField(blank=True, max_length=1, null=True, verbose_name='Conta receita')),
                ('definida_pelo_usuario', models.CharField(blank=True, max_length=1, null=True, verbose_name='Definida pelo usuário')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('descricao_padrao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição padrão')),
                ('id_conta_contabil', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID conta contábil')),
                ('nao_exibir', models.CharField(blank=True, max_length=1, null=True, verbose_name='Não exibir')),
                ('natureza', models.CharField(blank=True, max_length=30, null=True, verbose_name='Natureza')),
                ('tag_conta_contabil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag conta contábil')),
                ('tipo_categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo da categoria')),
                ('totalizadora', models.CharField(blank=True, max_length=1, null=True, verbose_name='Totalizadora')),
                ('transferencia', models.CharField(blank=True, max_length=1, null=True, verbose_name='Transferência')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['codigo', 'descricao'],
            },
        ),
    ]
