# Generated by Django 5.0.13 on 2026-04-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_contacorrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lancamento_omie', models.BigIntegerField(unique=True, verbose_name='Código do lançamento Omie')),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True, verbose_name='Código do cliente/fornecedor')),
                ('codigo_categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código da categoria')),
                ('codigo_lancamento_integracao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do lançamento integração')),
                ('codigo_tipo_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do tipo de documento')),
                ('chave_nfe', models.CharField(blank=True, max_length=60, null=True, verbose_name='Chave NFe')),
                ('numero_documento_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do documento fiscal')),
                ('numero_parcela', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número da parcela')),
                ('numero_pedido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do pedido')),
                ('nCodPedido', models.BigIntegerField(blank=True, null=True, verbose_name='Código do pedido')),
                ('id_conta_corrente', models.BigIntegerField(blank=True, null=True, verbose_name='ID da conta corrente')),
                ('id_origem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Origem')),
                ('operacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Operação')),
                ('tipo_agrupamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de agrupamento')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Data de previsão')),
                ('data_registro', models.DateField(blank=True, null=True, verbose_name='Data de registro')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('status_titulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status do título')),
                ('valor_documento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do documento')),
                ('retem_cofins', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_csll', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_inss', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_ir', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_iss', models.CharField(blank=True, max_length=1, null=True)),
                ('retem_pis', models.CharField(blank=True, max_length=1, null=True)),
                ('boleto_cGerado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boleto gerado')),
                ('boleto_cNumBancario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número bancário do boleto')),
                ('boleto_cNumBoleto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do boleto')),
                ('boleto_dDtEmBol', models.DateField(blank=True, null=True, verbose_name='Data de emissão do boleto')),
                ('boleto_nPerJuros', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Percentual de juros do boleto')),
                ('boleto_nPerMulta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Percentual de multa do boleto')),
                ('info_cimpapi', models.CharField(blank=True, max_length=1, null=True, verbose_name='Importado pela API')),
                ('info_d_inc', models.DateField(blank=True, null=True, verbose_name='Data de inclusão')),
                ('info_h_inc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de inclusão')),
                ('info_u_inc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuário de inclusão')),
                ('info_d_alt', models.DateField(blank=True, null=True, verbose_name='Data de alteração')),
                ('info_h_alt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora de alteração')),
                ('info_u_alt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuário de alteração')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento', '-codigo_lancamento_omie'],
            },
        ),
        migrations.CreateModel(
            name='ParametroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_empresa', models.SlugField(max_length=100, unique=True, verbose_name='Slug da empresa')),
                ('nome_empresa', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Parâmetro da Empresa',
                'verbose_name_plural': 'Parâmetros das Empresas',
                'ordering': ['nome_empresa'],
            },
        ),
    ]
