# Generated by Django 5.0.13 on 2026-04-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_contareceber_parametroempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da conta')),
                ('nivel', models.PositiveSmallIntegerField(editable=False, verbose_name='Nível')),
                ('sinal', models.CharField(choices=[('positivo', 'Positivo (+)'), ('negativo', 'Negativo (-)')], default='positivo', max_length=10, verbose_name='Sinal')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='dashboards.contadre', verbose_name='Conta pai')),
            ],
            options={
                'verbose_name': 'Conta DRE',
                'verbose_name_plural': 'Contas DRE',
                'ordering': ['nivel', 'ordem', 'nome'],
            },
        ),
    ]
