# Generated by Django 5.0.13 on 2026-04-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_contadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadre',
            name='sinal',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo (+)'), ('negativo', 'Negativo (-)')], max_length=10, null=True, verbose_name='Sinal'),
        ),
    ]
