# Generated by Django 5.0.13 on 2026-04-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_contadre_sinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeParaCategoriaDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deparas_dre', to='dashboards.categoria', verbose_name='Categoria')),
                ('conta_dre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_vinculadas', to='dashboards.contadre', verbose_name='Conta DRE')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deparas_dre', to='dashboards.parametroempresa', verbose_name='Empresa')),
            ],
        ),
    ]
