# Generated by Django 5.0.13 on 2026-04-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_deparacategoriadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroempresa',
            name='app_key_omie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='App Key Omie'),
        ),
        migrations.AddField(
            model_name='parametroempresa',
            name='app_secret_omie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='App Secret Omie'),
        ),
    ]
