# Generated by Django 5.0.13 on 2026-04-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_parametroempresa_app_key_omie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadre',
            name='sinal',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo (+)'), ('negativo', 'Negativo (-)'), ('resultado', 'Resultado (=)')], max_length=10, null=True, verbose_name='Sinal'),
        ),
    ]
