# Generated by Django 5.0.13 on 2026-04-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_contadre_sinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoContaDRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participa_de_formulas', to='dashboards.contadre', verbose_name='Conta de origem')),
                ('conta_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_formula', to='dashboards.contadre', verbose_name='Conta de resultado')),
            ],
            options={
                'verbose_name': 'Composição da Conta DRE',
                'verbose_name_plural': 'Composições das Contas DRE',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
