# Generated by Django 5.0.13 on 2026-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_indicadorconfiguracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo do departamento na Omie')),
                ('codigo_superior', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo do departamento superior')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descricao')),
                ('inativo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Inativo')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importacao')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Departamento Omie',
                'verbose_name_plural': 'Departamentos Omie',
                'ordering': ['descricao', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo da empresa na Omie')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razao social')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('inativo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Inativo')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importacao')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa Omie',
                'verbose_name_plural': 'Empresas Omie',
                'ordering': ['nome_fantasia', 'razao_social', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo do projeto na Omie')),
                ('codigo_integracao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Codigo de integracao')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do projeto')),
                ('inativo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Inativo')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importacao')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto Omie',
                'verbose_name_plural': 'Projetos Omie',
                'ordering': ['nome', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoContaCorrenteOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo do tipo de conta corrente na Omie')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descricao')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de importacao')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Conta Corrente Omie',
                'verbose_name_plural': 'Tipos de Conta Corrente Omie',
                'ordering': ['descricao', 'codigo'],
            },
        ),
    ]
