# Generated by Django 5.0.13 on 2026-05-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_indicadorconfiguracao_conta_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='DREProjetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linha', models.CharField(choices=[('conta', 'Conta DRE'), ('categoria', 'Categoria')], max_length=10, verbose_name='Tipo de linha')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor projetado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetados_dre', to='dashboards.categoria', verbose_name='Categoria')),
                ('conta_dre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetados', to='dashboards.contadre', verbose_name='Conta DRE')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetados_dre', to='dashboards.parametroempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'DRE Projetado',
                'verbose_name_plural': 'DRE Projetado',
                'ordering': ['ano', 'mes', 'conta_dre__ordem', 'categoria__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='dreprojetado',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_linha', 'conta_dre', 'categoria', 'ano', 'mes'), name='uniq_dre_projetado_linha_mes'),
        ),
    ]
