# Generated by Django 5.0.13 on 2026-05-27 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_dreprojetado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevistoRealizadoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('projetado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Projetado')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previstos_realizados', to='dashboards.categoria', verbose_name='Categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previstos_realizados_categoria', to='dashboards.parametroempresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Previsto / Realizado por Categoria',
                'verbose_name_plural': 'Previsto / Realizado por Categoria',
                'ordering': ['ano', 'mes', 'categoria__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='previstorealizadocategoria',
            constraint=models.UniqueConstraint(fields=('empresa', 'categoria', 'ano', 'mes'), name='uniq_previsto_realizado_categoria_mes'),
        ),
    ]
