from django.urls import path
from .views import (
    mover_conta_dre,
    dashboard_empresa,
    dashboard_dre_projetado,
    exportar_planilha_dre_projetado,
    importar_planilha_dre_projetado,
    parametros_empresa,
    parametros_gerais,
    parametros_resultado,
    dashboard_resultado,
    contas_dre,
    depara_categoria_dre,
    excluir_conta_dre,
    indicadores,
    exportar_planilha_depara,
    iniciar_sincronizacao_omie,
    reordenar_contas_dre,
    status_sincronizacao_omie,
)


urlpatterns = [
    path('<slug:slug>/', dashboard_empresa, name='dashboard_empresa'),
    path('<slug:slug>/resultado/', dashboard_resultado, name='dashboard_resultado'),
    path('<slug:slug>/dre-vs-projetado/', dashboard_dre_projetado, name='dashboard_dre_projetado'),
    path('<slug:slug>/dre-vs-projetado/exportar/', exportar_planilha_dre_projetado, name='exportar_planilha_dre_projetado'),
    path('<slug:slug>/dre-vs-projetado/importar/', importar_planilha_dre_projetado, name='importar_planilha_dre_projetado'),
    path('<slug:slug>/parametros/', parametros_empresa, name='parametros_empresa'),
    path('<slug:slug>/parametros/gerais/', parametros_gerais, name='parametros_gerais'),
    path('<slug:slug>/parametros/resultado/', parametros_resultado, name='parametros_resultado'),
    path('<slug:slug>/parametros/sincronizacao-omie/iniciar/', iniciar_sincronizacao_omie, name='iniciar_sincronizacao_omie'),
    path('<slug:slug>/parametros/sincronizacao-omie/status/<str:task_id>/', status_sincronizacao_omie, name='status_sincronizacao_omie'),
    path('<slug:slug>/parametros/contas-dre/', contas_dre, name='contas_dre'),
    path('<slug:slug>/parametros/indicadores/', indicadores, name='indicadores'),
    path('<slug:slug>/parametros/contas-dre/excluir/<int:id>/', excluir_conta_dre, name='excluir_conta_dre'),
    path('<slug:slug>/parametros/de-para/', depara_categoria_dre, name='depara_categoria_dre'),
    path('<slug:slug>/parametros/de-para/exportar/', exportar_planilha_depara, name='exportar_planilha_depara'),
    path('<slug:slug>/parametros/contas-dre/reordenar/', reordenar_contas_dre, name='reordenar_contas_dre'),
    path('<slug:slug>/parametros/contas-dre/mover/<int:id>/<str:direcao>/', mover_conta_dre, name='mover_conta_dre'),
]
